### ISSUE TITLE
API operation to list results

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kubtest#250]
The proposed Dashboard #204 requires a GET /executions operation to list all executions with the possibility to filter on namespace, start-time (range), status (running, passed, failed), script-name, script-type

No authentication needed at the api-server level.

Not sure about paging at this point... !?

**Comment by exu** [comment]
we have /executions endpoint
you can get particular script execution
or if you’ll pass - as script name - recent executions


no pages and no filters for now :slightly_smiling_face:
GET/scripts​/{id}​/executions  Get all script executions

**Comment by olensmar** [comment]
thanks @exu - @hamzahsn maybe GET /scripts/-/executions can work as a starting point if you want to do client-side filtering?

**Comment by hamzahsn** [comment]
Thanks @exu  @olensmar for clarifying, filtering data as we talked with @olensmar yesterday that it could be made on the client-side, as for now, we need to keep it simple so as you suggested we can use `GET /scripts/{id}/executions` 🙂
