### ISSUE TITLE
Execution object should have script-type instead of script-content (to review)

### ISSUE THREAD

**Issue by exu** [kubeshop/kubtest#252]
we need to rethink removing this content from execution - let’s elaborate on this a little:

1. currently content is in ExecutionRequest object

2. Execution is type returned from executor (executor internally need to store it somewhere - I’m currently using it for storing this in mongo - didn’t introduce any mappers and additional types to simplify stuff)

3. So if I remove this from Execution and Leave in ExecutionRequest only I need to hide implementation details somehow in executor. as I’m piping Execution in workers queue (not ExecutionRequest)

**Comment by olensmar** [comment]
also need to consider the case when there is no script-content - scripts are retrieved from Git at run-time

**Comment by exu** [comment]
This task is not needed anymore as of recent data model refactor
