### ISSUE TITLE
Helm charts - add some auto-version-bumping mechanisms

### ISSUE THREAD

**Issue by exu** [kubeshop/kubtest#261]
**Describe the enhancement you'd like to see**

as an software engineer I don't want to do things 'by hand' 
find nice way to autogenerate helm charts on `kubtest` or any `kubtests-executor-*` 

additionally all images are working on `latest` tag - we should fix appVersion of helm chart with given version od any kubtest component to limit bugs and make debugging easier

Consider migrating repository to https://artifacthub.io/ 

Flows: 

Updating any component prod version e.g. v1.0.1:
- go to component repo code
- do change in kubtest component (e.g. api server)
- git tag v1.0.1 && git push --tags
- build docker image
- run helm chart build for component - bump version + set app version to v1.0.1
- run pipeline for building main `kubtest` helm chart
     + we need to put v1.0.1 in api server in dependency array
     + bump version in Chart.yaml for kubtest

Making development change (e.g. on feature branch) 
- go to component repo code
- do change in kubtest component (e.g. api server)
- git tag v1.0.1-beta1 && git push --tags
- build docker image
- run helm chart build for component - bump version + set app version to v1.0.1-beta1
- run pipeline for building main `kubtest` helm chart
     + we need to put v1.0.1 in api server in dependency array
     + generate chart development version (if current version is 1.0.0 could be for example 1.0.1-fasc45c223 or 1.0.1-alpha23)

Would be nice to have info on slack when notifier will be completed :)

**Comment by jasmingacic** [comment]
* Charts for each component should live in the same repo as the components 
* we need to manually increment version for each chart we can do this automagically but i'm convinced that this will introduce more problems down the line. The flow could be something like once a repository_dispatch has been issued we can pull for version of the dependency and inject that into values.yaml and then build it.
* I've also added repository_dispatch trigger to helm-charts repo but all it does is build what we have in the master
