### ISSUE TITLE
add input for backend URL to dashboard

### ISSUE THREAD

**Issue by olensmar** [kubeshop/kubtest#293]
when a user accesses dashboard.kubtest.io they will need to specify the endpoint to their API server (exposed via ingress from #284 ) 
- could we save this to local-storage so user doesn't have to enter it every time?
- we should show/point-to instructions on how to get the URL required from a kubtest installation

**Comment by hamzahsn** [comment]
- right now we are using local-storage for the storing the address.
- right now the URL is printed to the console, so do we need to add extra requests from the user (do you want to see tests running visually?...) ?
