### ISSUE TITLE
Remove hardcoded "v1" from client implementation

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/kubtest#308]
As @nicufk mentioned in #297 
/kubtest/pkg/api/client/direct.go and /kubtest/pkg/api/client/proxy.go and others have hardcoded `v1` in uri strings.

**Comment by exu** [comment]
should we start versioning our clients and apis in general? 
e.g. KubtestApiClientV1 KubtestApiV1 (handled on /v1 route) in case of braking API changes we could have both handled in some period of time @nicufk @jasmingacic what do you think ?

**Comment by olensmar** [comment]
> should we start versioning our clients and apis in general?
> e.g. KubtestApiClientV1 KubtestApiV1 (handled on /v1 route) in case of braking API changes we could have both handled in some period of time @nicufk @jasmingacic what do you think ?

makes sense to me
