### ISSUE TITLE
Implement example executor

### ISSUE THREAD

**Issue by exu** [kubeshop/kubtest#52]
Curl based simple one-node executor, status storage in-memory - for documentation purpose

1. create executor from template 
2. clear mongodb
3. implement runner (create CURLRunnel based on Example runner) 
4. remove worker (we will go with single node) 
5.  run inside Start endpoint as goroutine

**Comment by olensmar** [comment]
Would this be in a dedicated repo? i.e. kubtest-executor-sample ?
